package rdl

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/antchfx/xmlquery"
)

func TestAddParameter_Individual_LayoutAutoGenerated(t *testing.T) {
	// Create a fresh report with no parameters.
	spec := CreateSpec{
		Target:      filepath.Join(t.TempDir(), "fresh.rdl"),
		Title:       "Test Report",
		Orientation: "Portrait",
	}
	_, err := Create(spec, false)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	doc, err := Load(spec.Target)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	// Add parameters individually (the atomic path, not ManageParameters).
	params := []ParameterAdd{
		{Name: "pvc_UserId", Type: "String", Prompt: "User ID"},
		{Name: "pvc_Theme", Type: "String", Prompt: "Theme"},
		{Name: "pvc_ReportEntity", Type: "String", Prompt: "Portfolio"},
		{Name: "pvc_CurrencyISO", Type: "String", Prompt: "Currency"},
		{Name: "pvc_FromDate", Type: "String", Prompt: "From Date"},
		{Name: "pvc_ToDate", Type: "String", Prompt: "To Date"},
		{Name: "pvc_Benchmark1", Type: "String", Hidden: true},
	}
	for _, p := range params {
		_, err := doc.AddParameterOp(p)
		if err != nil {
			t.Fatalf("AddParameterOp(%s): %v", p.Name, err)
		}
	}

	// Save and reload to test persisted state.
	re := reloadSaved(t, doc)

	// Verify all parameters exist.
	if got := len(re.ListParameters()); got != 7 {
		t.Errorf("param count = %d, want 7", got)
	}

	// Verify ReportParametersLayout exists.
	layout := xmlquery.FindOne(re.Root(), "//ReportParametersLayout")
	if layout == nil {
		t.Fatal("ReportParametersLayout not generated — expected auto-generation after individual AddParameter calls")
	}

	// Verify grid has 6 cells (visible params only, hidden excluded).
	cells := xmlquery.Find(layout, ".//CellDefinition")
	if got := len(cells); got != 6 {
		t.Errorf("CellDefinition count = %d, want 6 (visible params only)", got)
	}

	// Verify NumberOfRows is correct (6 visible params in 2 columns = 3 rows).
	nr := xmlquery.FindOne(layout, ".//NumberOfRows")
	if nr == nil {
		t.Fatal("NumberOfRows missing from grid")
	}
	if got := strings.TrimSpace(nr.InnerText()); got != "3" {
		t.Errorf("NumberOfRows = %s, want 3", got)
	}

	// Verify hidden param is NOT in the grid.
	for _, cell := range cells {
		pn := child(cell, "ParameterName")
		if pn != nil && strings.TrimSpace(pn.InnerText()) == "pvc_Benchmark1" {
			t.Error("hidden parameter pvc_Benchmark1 should not be in the layout grid")
		}
	}

	// Verify validation passes.
	rv := re.Validate()
	for _, issue := range rv.Issues {
		if issue.Severity == SeverityError {
			t.Errorf("validation error: %s", issue.Message)
		}
	}
}

func TestRemoveParameter_LayoutRegenerated(t *testing.T) {
	doc := mustLoad(t)
	// sample.rdl has Region, StartDate (visible) and Hidden (hidden).
	// Remove one visible param — layout should be regenerated.
	_, err := doc.RemoveParameterOp("Region")
	if err != nil {
		t.Fatalf("RemoveParameterOp: %v", err)
	}

	re := reloadSaved(t, doc)

	// Verify layout still exists with 1 visible param (StartDate).
	layout := xmlquery.FindOne(re.Root(), "//ReportParametersLayout")
	if layout == nil {
		t.Fatal("ReportParametersLayout missing after removing a parameter — expected regeneration")
	}

	cells := xmlquery.Find(layout, ".//CellDefinition")
	if got := len(cells); got != 1 {
		t.Errorf("CellDefinition count = %d, want 1 (StartDate only)", got)
	}
}
